apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
        - name: library
          image: thirumavalavan1506/library-0.0.1
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: library
spec:
  selector:
    app: library
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090